-- Insert Expense Categories
INSERT INTO expense_categories (name, account_number, description, is_active, created_at, updated_at) VALUES
('SSS/HDMF/PHIC Premium Expense', '4001', 'SSS/HDMF/PHIC Premium Expense', TRUE, NOW(), NOW()),
('13th Month Expense', '4002', '13th Month Expense', TRUE, NOW(), NOW()),
('Executive Allowance', '4003', 'Executive Allowance', TRUE, NOW(), NOW()),
('Employee Incentives', '4004', 'Employee Incentives', TRUE, NOW(), NOW()),
('Employee Benefits', '4005', 'Employee Benefits', TRUE, NOW(), NOW()),
('Office Rent Expense', '4006', 'Office Rent Expense', TRUE, NOW(), NOW()),
('Membership and Association Dues', '4007', 'Membership and Association Dues', TRUE, NOW(), NOW()),
('Electricity and Water Expense', '4008', 'Electricity and Water Expense', TRUE, NOW(), NOW()),
('Parking Fee', '4009', 'Parking Fee', TRUE, NOW(), NOW()),
('Telephone Expense', '4010', 'Telephone Expense', TRUE, NOW(), NOW()),
('Internet Expense', '4011', 'Internet Expense', TRUE, NOW(), NOW()),
('Communication Expense', '4012', 'Communication Expense', TRUE, NOW(), NOW()),
('Office Supplies Expense', '4013', 'Office Supplies Expense', TRUE, NOW(), NOW()),
('Administrative Expense', '4014', 'Administrative Expense', TRUE, NOW(), NOW()),
('Administrative Expense:AFC', '4015', 'Administrative Expense - AFC', TRUE, NOW(), NOW()),
('Administrative Expense:AUDIT', '4016', 'Administrative Expense - AUDIT', TRUE, NOW(), NOW()),
('Administrative Expense:HRD', '4017', 'Administrative Expense - HRD', TRUE, NOW(), NOW()),
('Taxes and Licenses Expense', '4018', 'Taxes and Licenses Expense', TRUE, NOW(), NOW()),
('Transportation Expense-Regular', '4019', 'Transportation Expense - Regular', TRUE, NOW(), NOW()),
('Transportation Expense-Outsourc', '4020', 'Transportation Expense - Outsourced', TRUE, NOW(), NOW()),
('Representation Expense', '4021', 'Representation Expense', TRUE, NOW(), NOW()),
('Repair & Maintenance Expense', '4022', 'Repair & Maintenance Expense', TRUE, NOW(), NOW()),
('Pantry Supplies', '4023', 'Pantry Supplies', TRUE, NOW(), NOW()),
('Insurance Expense', '4024', 'Insurance Expense', TRUE, NOW(), NOW()),
('Professional & Retainer''s Fee', '4025', 'Professional & Retainer''s Fee', TRUE, NOW(), NOW()),
('Depreciation Expense', '4026', 'Depreciation Expense', TRUE, NOW(), NOW()),
('Gift and Donations', '4027', 'Gift and Donations', TRUE, NOW(), NOW()),
('Interest Expense', '4028', 'Interest Expense', TRUE, NOW(), NOW()),
('Bank and Other Charges', '4029', 'Bank and Other Charges', TRUE, NOW(), NOW()),
('Printer Ink Expense', '4030', 'Printer Ink Expense', TRUE, NOW(), NOW()),
('Advertising Expense', '4031', 'Advertising Expense', TRUE, NOW(), NOW()),
('Car Plan-DP', '4032', 'Car Plan - Down Payment', TRUE, NOW(), NOW()),
('Transportation Expense- HO', '4033', 'Transportation Expense - HO', TRUE, NOW(), NOW()),
('Separation Pay', '4034', 'Separation Pay', TRUE, NOW(), NOW()),
('Rent Expense', '4035', 'Rent Expense', TRUE, NOW(), NOW()),
('Miscellaneous Expense', '4036', 'Miscellaneous Expense', TRUE, NOW(), NOW()),
('Utilities Expense', '4037', 'Utilities Expense', TRUE, NOW(), NOW()),
('Software Developments', '4038', 'Software Developments', TRUE, NOW(), NOW()),
('Fuel and Oil', '4039', 'Fuel and Oil', TRUE, NOW(), NOW()),
('PT&T', '4040', 'PT&T', TRUE, NOW(), NOW()),
('Amortization', '4041', 'Amortization', TRUE, NOW(), NOW()),
('Registration Expenses', '4042', 'Registration Expenses', TRUE, NOW(), NOW()),
('Legal Expense', '4043', 'Legal Expense', TRUE, NOW(), NOW()),
('Lodging Fee', '4044', 'Lodging Fee', TRUE, NOW(), NOW()),
('Notarial Fee', '4045', 'Notarial Fee', TRUE, NOW(), NOW()),
('IT Expenses', '4046', 'IT Expenses', TRUE, NOW(), NOW()),
('Social & Rec. Expense', '4047', 'Social & Recreation Expense', TRUE, NOW(), NOW()),
('Foreign Exchance Loss', '4048', 'Foreign Exchange Loss', TRUE, NOW(), NOW()),
('Write-off', '4049', 'Write-off', TRUE, NOW(), NOW()),
('Deferred tax expense', '4050', 'Deferred Tax Expense', TRUE, NOW(), NOW()),
('Training & Seminar Expense', '4051', 'Training & Seminar Expense', TRUE, NOW(), NOW());
